
# This is a template Makefile generated by rpcgen

# Parameters

CLIENT = rpc_checkIP_client
SERVER = rpc_checkIP_server

SOURCES_CLNT.c = 
SOURCES_CLNT.h = 
SOURCES_SVC.c = 
SOURCES_SVC.h = 
SOURCES.x = rpc_checkIP.x

TARGETS_SVC.c = rpc_checkIP_svc.c rpc_checkIP_server.c rpc_checkIP_xdr.c 
TARGETS_CLNT.c = rpc_checkIP_clnt.c rpc_checkIP_client.c rpc_checkIP_xdr.c 
TARGETS = rpc_checkIP.h rpc_checkIP_xdr.c rpc_checkIP_clnt.c rpc_checkIP_svc.c rpc_checkIP_client.c rpc_checkIP_server.c

OBJECTS_CLNT = $(SOURCES_CLNT.c:%.c=%.o) $(TARGETS_CLNT.c:%.c=%.o)
OBJECTS_SVC = $(SOURCES_SVC.c:%.c=%.o) $(TARGETS_SVC.c:%.c=%.o)
# Compiler flags 

CFLAGS += -g
LDLIBS += -lnsl -lm
RPCGENFLAGS = 

# Targets 

all : $(CLIENT) $(SERVER)

$(TARGETS) : $(SOURCES.x) 
	rpcgen $(RPCGENFLAGS) $(SOURCES.x)

$(OBJECTS_CLNT) : $(SOURCES_CLNT.c) $(SOURCES_CLNT.h) $(TARGETS_CLNT.c) 

$(OBJECTS_SVC) : $(SOURCES_SVC.c) $(SOURCES_SVC.h) $(TARGETS_SVC.c) 

$(CLIENT) : $(OBJECTS_CLNT) 
	$(LINK.c) -o $(CLIENT) $(OBJECTS_CLNT) $(LDLIBS) 

$(SERVER) : $(OBJECTS_SVC) 
	$(LINK.c) -o $(SERVER) $(OBJECTS_SVC) $(LDLIBS)

 clean:
	 $(RM) core $(TARGETS) $(OBJECTS_CLNT) $(OBJECTS_SVC) $(CLIENT) $(SERVER)

