/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rpc_checkIP.h"

bool_t
xdr_ip_str (XDR *xdrs, ip_str *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, MAXLEN))
		 return FALSE;
	return TRUE;
}
