/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPC_CHECKIP_H_RPCGEN
#define _RPC_CHECKIP_H_RPCGEN

#include <rpc/rpc.h>
#include <math.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXLEN 19

typedef char *ip_str;

#define CHECK_IP 0x2fffffff
#define CHECK_IP_1 1

#if defined(__STDC__) || defined(__cplusplus)
#define CHECKIP 1
extern  int * checkip_1(ip_str *, CLIENT *);
extern  int * checkip_1_svc(ip_str *, struct svc_req *);
extern int validateIPv4(char* address, char* ip, int* prefix);
extern int check_ip_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define CHECKIP 1
extern  int * checkip_1();
extern  int * checkip_1_svc();
extern int check_ip_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_ip_str (XDR *, ip_str*);

#else /* K&R C */
extern bool_t xdr_ip_str ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPC_CHECKIP_H_RPCGEN */
