/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rpc_checkIP.h"
#include <math.h>

int *
checkip_1_svc(ip_str *argp, struct svc_req *rqstp)
{
	static int  result;      
        char* ip;
        int prefix;
        char* err;
        
        printf("Got Client request.\n");
        printf("Checking IP %s.\n", *argp);

	/*
	 * insert server code here
	 */    
        result = validateIPv4(*argp, ip, &prefix);
        if(result != 0)
            return &result;

        result = 0;        
	return &result;
}
int validateIPv4(char* address, char* ip, int* prefix_int){

        char* prefix;
        int ipv4[4];
     

        ip = strtok(address,"/");
	prefix = strtok(NULL,"");
        
        printf("ip: %s \n", ip);
        printf("netmask: %s \n", prefix);
     
        
        
	if(prefix == NULL){
		printf("invalid netmask!\n");
		return 1;
	}
        char *tmpStr;
        tmpStr = strtok(address,".");
        for(int i = 0; i < 4; i++){
            if(tmpStr == NULL){
                printf("invalid adress!\n");
                return 3;
            }
            ipv4[i] = atoi(tmpStr);
            tmpStr = strtok(NULL,".");
        }
        
        printf("ip = %d.%d.%d.%d\n",ipv4[0],ipv4[1],ipv4[2],ipv4[3]);
        
        *prefix_int = atoi(prefix);    
	if(*prefix_int >32 || *prefix_int <1){
            printf("invalid prefix!\n");
            return 2;
	}
        int tmp1 = *prefix_int/8;
        int maske[4] = {0,0,0,0};
        for(int i = 0; i < tmp1; i++){
            maske[i] = ipv4[i];
        }
        for(int i = 0; i != *prefix_int%8; i++){
            if((ipv4[tmp1] - pow(2, 7-i)) > 0)
                maske[tmp1] += pow(2, 7-i);
        }
        printf("mask = %d.%d.%d.%d\n",maske[0],maske[1],maske[2],maske[3]);
        
        return 0;
}
